services:
  qdrant:
    image: qdrant/qdrant@sha256:057ee3a8da769fe7310dd3537b4dc7583bf87a95ce8ac43c0af5a46bc580d1fc
    container_name: enterprise-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: enterprise-rag-api
    ports:
      - "8000:8000"
    environment:
      QDRANT_URL: http://qdrant:6333
      OLLAMA_URL: http://ollama:11434
      CHUNKS_PATH: /app/data/processed/chunks_fixed.jsonl
      QDRANT_COLLECTION: enterprise_knowledge_fixed_bge_small
      EMBEDDING_MODEL: BAAI/bge-small-en-v1.5
      GENERATION_MODEL: qwen3:4b-instruct
      GENERATION_TIMEOUT_SECONDS: "120"
      DENSE_WEIGHT: "0.7"
      BM25_WEIGHT: "0.3"
      RRF_K: "60"
      RETRIEVAL_TOP_K: "10"
      MAX_CONTEXT_TOKENS: "4000"
      MAX_CONTEXT_SOURCES: "6"
      MAX_CONCURRENT_GENERATIONS: "1"
    volumes:
      - ./data/processed:/app/data/processed:ro
    depends_on:
      qdrant:
        condition: service_started
      ollama:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69
    container_name: enterprise-rag-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - api
    restart: unless-stopped

  grafana:
    image: grafana/grafana@sha256:ab5cb380e3ff3172d6c8bd2e7cfd31cce977d2881b260e1f5bc089bf0b759b43
    container_name: enterprise-rag-grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_storage:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus

    restart: unless-stopped

  ollama:
    image: ollama/ollama@sha256:b88c73ace3e115f8ec53dc8761ae1c0aabfa675406e3681786b98757ce050f42
    container_name: enterprise-rag-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test:
        [
          "CMD",
          "ollama",
          "list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  qdrant_storage:
    external: true
    name: docker_qdrant_storage
  grafana_storage:

  ollama_models:
